version: '2'

services:

  chauffeur:
    build: .
    ports:
      - "8085:8085"
    networks:
      - network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/chauffeur"
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
      #      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/"
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"


networks:
  network:
