version: '2'

services:

  vehicule:
    build: .
    ports:
      - "8083:8083"
    networks:
      - network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_PORT: 3300
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/vehicule"
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/"
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"


networks:
  network:
